from dotenv import load_dotenv

load_dotenv()

SIMILARITY_THRESHOLD = 80
FACE_SIMILARITY_THRESHOLD = 0.7
REKOGNITION_THRESHOLD = 70
PDF_DPI = 200
MIN_PAGES_REQUIRED = 3
MAX_PDF_SIZE = 10
MAX_WORKERS = 4